require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeaningsController do

  # This should return the minimal set of attributes required to create a valid
  # Meaning. As you add validations to Meaning, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeaningsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all meanings as @meanings" do
      meaning = Meaning.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meanings).should eq([meaning])
    end
  end

  describe "GET show" do
    it "assigns the requested meaning as @meaning" do
      meaning = Meaning.create! valid_attributes
      get :show, {:id => meaning.to_param}, valid_session
      assigns(:meaning).should eq(meaning)
    end
  end

  describe "GET new" do
    it "assigns a new meaning as @meaning" do
      get :new, {}, valid_session
      assigns(:meaning).should be_a_new(Meaning)
    end
  end

  describe "GET edit" do
    it "assigns the requested meaning as @meaning" do
      meaning = Meaning.create! valid_attributes
      get :edit, {:id => meaning.to_param}, valid_session
      assigns(:meaning).should eq(meaning)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Meaning" do
        expect {
          post :create, {:meaning => valid_attributes}, valid_session
        }.to change(Meaning, :count).by(1)
      end

      it "assigns a newly created meaning as @meaning" do
        post :create, {:meaning => valid_attributes}, valid_session
        assigns(:meaning).should be_a(Meaning)
        assigns(:meaning).should be_persisted
      end

      it "redirects to the created meaning" do
        post :create, {:meaning => valid_attributes}, valid_session
        response.should redirect_to(Meaning.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meaning as @meaning" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meaning.any_instance.stub(:save).and_return(false)
        post :create, {:meaning => {}}, valid_session
        assigns(:meaning).should be_a_new(Meaning)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Meaning.any_instance.stub(:save).and_return(false)
        post :create, {:meaning => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meaning" do
        meaning = Meaning.create! valid_attributes
        # Assuming there are no other meanings in the database, this
        # specifies that the Meaning created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Meaning.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => meaning.to_param, :meaning => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested meaning as @meaning" do
        meaning = Meaning.create! valid_attributes
        put :update, {:id => meaning.to_param, :meaning => valid_attributes}, valid_session
        assigns(:meaning).should eq(meaning)
      end

      it "redirects to the meaning" do
        meaning = Meaning.create! valid_attributes
        put :update, {:id => meaning.to_param, :meaning => valid_attributes}, valid_session
        response.should redirect_to(meaning)
      end
    end

    describe "with invalid params" do
      it "assigns the meaning as @meaning" do
        meaning = Meaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Meaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => meaning.to_param, :meaning => {}}, valid_session
        assigns(:meaning).should eq(meaning)
      end

      it "re-renders the 'edit' template" do
        meaning = Meaning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Meaning.any_instance.stub(:save).and_return(false)
        put :update, {:id => meaning.to_param, :meaning => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meaning" do
      meaning = Meaning.create! valid_attributes
      expect {
        delete :destroy, {:id => meaning.to_param}, valid_session
      }.to change(Meaning, :count).by(-1)
    end

    it "redirects to the meanings list" do
      meaning = Meaning.create! valid_attributes
      delete :destroy, {:id => meaning.to_param}, valid_session
      response.should redirect_to(meanings_url)
    end
  end

end
